[package]
name = "ch15_02_smart_pointer_mybox"
version = "0.1.0"
authors = ["sunakan <sunakn03@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
